name: Hostloc Auto Task

on:
  schedule:
    - cron: '0 16 * * *' # UTC时间0点和12点（北京时间8点和20点）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Set npm registry to official
        run: npm config set registry https://registry.npmjs.org/
        
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Run hostloc automation
        env:
          HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
          HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NODE_ENV: production
        run: node index.js
